Examples/SportsStore_CH11/SportsStore/Models/Cart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SportsStore.Models
{
    public class Cart
    {
        private List<CartLine> lineCollection = new List<CartLine>();

        public virtual IEnumerable<CartLine> Lines => lineCollection;

        public virtual void AddItem(Product product, int quantity)
        {
            CartLine line = lineCollection
                .Where(p => p.Product.ProductID == product.ProductID)
                .FirstOrDefault();

            if(line == null)
            {
                CartLine lineItem = new CartLine()
                {
                    Product = product,
                    Quantity = quantity
                };

                lineCollection.Add(lineItem);
            }
            else
            {
                line.Quantity += quantity;
            }
        }

        public virtual void RemoveLine(Product product) => lineCollection.RemoveAll(l => l.Product.ProductID == product.ProductID);

        public virtual decimal ComputeTotalValue() => lineCollection.Sum(li => li.Product.Price * li.Quantity);

        public virtual void Clear() => lineCollection.Clear();
    }

    public class CartLine
    {
        public int CartLineID { get; set; }
        public Product Product { get; set; }
        public int Quantity { get; set; }

    }
}

Examples/SportsStore_CH11/SportsStore/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore.Infrastructure;
using SportsStore.Models;
using SportsStore.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SportsStore.Controllers
{
    public class CartController : Controller
    {
        private IProductRepository prodRepo;
        private Cart cart;
        
        public CartController(IProductRepository prodRepo, Cart cartService)
        {
            this.prodRepo = prodRepo;
            cart = cartService;
        }

        public RedirectToActionResult AddToCart(int productId, string ReturnURL)
        {
            Product prod = prodRepo.Products.FirstOrDefault(p => p.ProductID == productId);

            if(prod != null)
            {
                cart.AddItem(prod, 1);
            }

            return RedirectToAction("Index", new { ReturnURL });
        }

        public RedirectToActionResult RemoveFromCart(int productId, string returnURL)
        {
            Product prod = prodRepo.Products.FirstOrDefault(p => p.ProductID == productId);

            if(prod != null)
            {
                cart.RemoveLine(prod);
            }

            return RedirectToAction("Index", new { returnURL });
        }

        public IActionResult Index(string returnURL)
        {
            CartIndexViewModel model = new CartIndexViewModel()
            {
                Cart = cart,
                ReturnUrl = returnURL
            };

            return View(model);
        }
    }
}

Examples/SportsStore_CH11/SportsStore/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SportsStore.Controllers
{
    public class OrderController : Controller
    {
        private IOrderRepository orderRepo;
        private Cart cart;

        public OrderController(IOrderRepository orderRepo, Cart cart)
        {
            this.orderRepo = orderRepo;
            this.cart = cart;
        }

        public IActionResult Checkout() => View(new Order());

        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            if(cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your cart is empty!");
            }

            if (ModelState.IsValid)
            {
                order.Lines = cart.Lines.ToArray();
                orderRepo.SaveOrder(order);
                return RedirectToAction("Completed");
            }
            else
            {
                return View(order);
            }
        }

        public IActionResult Completed()
        {
            cart.Clear();
            return View();
        }

        public IActionResult List() => View(orderRepo.Orders.Where(o => !o.Shipped));

        [HttpPost]
        public IActionResult MarkShipped(int orderId)
        {
            Order order = orderRepo.Orders.FirstOrDefault(o => o.OrderID == orderId);

            if(order != null)
            {
                order.Shipped = true;
                orderRepo.SaveOrder(order);
            }

            return RedirectToAction("List");
        }
    }
}

Examples/SportsStore_CH11/SportsStore/Views/Cart/Index.cshtml
@model CartIndexViewModel

<h2>Your Cart</h2> 
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Quantity</th>
            <th>Item</th>
            <th class="text-right">Price</th>
            <th class="text-right">Subtotal</th>
        </tr>
    </thead>
    <tbody>
        @foreach(CartLine cartLine in Model.Cart.Lines)
        {
        <tr>
            <td class="text-center">@cartLine.Quantity</td>
            <td class="text-left">@cartLine.Product.Name</td>
            <td class="text-right">@($"{cartLine.Product.Price:C2}")</td>
            <td class="text-center">@($"{cartLine.Product.Price * cartLine.Quantity:C2}")</td>

            <td>
                <form asp-action="RemoveFromCart" method="post">
                    <input type="hidden" name="productId" value="@cartLine.Product.ProductID"/>
                    <input type="hidden" name="returnURL" value="@Model.ReturnUrl"/>
                    <button type="submit" class="btn btn-sm btn-danger">
                        Remove
                    </button>
                </form>
            </td>
        </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Total:</td>
            <td class="text-right">
                @($"{Model.Cart.ComputeTotalValue():C2}")
            </td>
        </tr>
    </tfoot>
</table>

<div class="text-center">
    <a class="btn btn-primary" href="@Model.ReturnUrl">Continue Shopping</a>

    <a class="btn btn-primary" asp-action="Checkout" asp-controller="Order">
        Checkout
    </a>
</div>