Assignments/DealershipEFCore/DealershipEFCore/Controllers/AllVehiclesController.cs
using DealershipEFCore.Models;
using DealershipEFCore.Models.RepositoryInterfaces;
using DealershipEFCore.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DealershipEFCore.Controllers
{
    public class AllVehiclesController : Controller
    {
        private IAllVehicleRepository vehicleRepo;
        private int pageSize = 10;

        public AllVehiclesController(IAllVehicleRepository vehicleRepo)
        {
            this.vehicleRepo = vehicleRepo;
        }
        public IActionResult List(int page = 1)
        {
            ViewBag.Title = "All Vehicles In Dealership";
            ViewBag.PageAction = "List";

            IEnumerable<Vehicle> allVehicles = vehicleRepo.Vehicles
                .OrderBy(v => v.VehicleID)
                .Skip((page - 1) * pageSize)
                .Take(pageSize);

            PagingInfo pageInfo = new PagingInfo()
            {
                CurrentPage = page,
                ItemsPerPage = pageSize,
                TotalItems = vehicleRepo.Vehicles.Count()
            };

            VehicleListViewModel vModel = new VehicleListViewModel()
            {
                Vehicles = allVehicles,
                PagingInfo = pageInfo
            };

            return View(vModel);
        }
    }
}

Assignments/DealershipEFCore/DealershipEFCore/Controllers/EmployeesController.cs
using DealershipEFCore.Models;
using DealershipEFCore.Models.RepositoryInterfaces;
using DealershipEFCore.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DealershipEFCore.Controllers
{
    public class EmployeesController : Controller
    {
        private IEmployeeRepository employeeRepo;
        private int pageSize = 5;

        public EmployeesController(IEmployeeRepository employeeRepo)
        {
            this.employeeRepo = employeeRepo;
        }

        public IActionResult Index()
        {
            ViewBag.Title = "Employee Info";
            return View();
        }
        public IActionResult ListEmployed(int page = 1)
        {
            ViewBag.Title = "Employee Info";
            ViewBag.Employed = "Currently Employed";
            ViewBag.PageAction = "ListEmployed";

            IEnumerable<Employee> employedEmps = employeeRepo.Employees
                .Where(e => e.IsCurrentlyEmployed == true)
                .OrderBy(e => e.EmployeeID)
                .Skip((page - 1) * pageSize)
                .Take(pageSize);

            PagingInfo pageInfo = new PagingInfo()
            {
                CurrentPage = page,
                ItemsPerPage = pageSize,
                TotalItems = employeeRepo.Employees.Where(e => e.IsCurrentlyEmployed == true).Count()
            };

            EmployeeListViewModel vModel = new EmployeeListViewModel()
            {
                Employees = employedEmps,
                PagingInfo = pageInfo
            };

            return View(vModel);
        }

        public IActionResult ListNotEmployed(int page = 1)
        {
            ViewBag.Title = "Employee Info";
            ViewBag.Employed = "Not Currently Employed";
            ViewBag.PageAction = "ListNotEmployed";

            IEnumerable<Employee> notEmployedEmps = employeeRepo.Employees
                .Where(e => e.IsCurrentlyEmployed == false)
                .OrderBy(e => e.EmployeeID)
                .Skip((page - 1) * pageSize)
                .Take(pageSize);

            PagingInfo pageInfo = new PagingInfo()
            {
                CurrentPage = page,
                ItemsPerPage = pageSize,
                TotalItems = employeeRepo.Employees.Where(e => e.IsCurrentlyEmployed == false).Count()
            };

            EmployeeListViewModel vModel = new EmployeeListViewModel()
            {
                Employees = notEmployedEmps,
                PagingInfo = pageInfo
            };

            return View(vModel);
        }
    }
}

Assignments/DealershipEFCore/DealershipEFCore/Controllers/SoldVehiclesController.cs
using DealershipEFCore.Models;
using DealershipEFCore.Models.RepositoryInterfaces;
using DealershipEFCore.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DealershipEFCore.Controllers
{
    public class SoldVehiclesController : Controller
    {
        private ISoldVehicleRepository vehicleRepo;
        private int pageSize = 10;

        public SoldVehiclesController(ISoldVehicleRepository vehicleRepo)
        {
            this.vehicleRepo = vehicleRepo;
        }
        public IActionResult List(int page = 1)
        {
            ViewBag.Title = "Vehicles Sold";
            ViewBag.PageAction = "List";


            IEnumerable<Vehicle> vehiclesSold = vehicleRepo.Vehicles
                .OrderBy(v => v.VehicleID)
                .Skip((page - 1) * pageSize)
                .Take(pageSize);

            PagingInfo pageInfo = new PagingInfo()
            {
                CurrentPage = page,
                ItemsPerPage = pageSize,
                TotalItems = vehicleRepo.Vehicles.Count()
            };

            VehicleListViewModel vModel = new VehicleListViewModel()
            {
                Vehicles = vehiclesSold,
                PagingInfo = pageInfo
            };

            return View(vModel);
        }
    }
}

Assignments/DealershipEFCore/DealershipEFCore/Views/Shared/PagingInfoPartial.cshtml
<div class="container text-center mb-5">
    <div page-model="@Model.PagingInfo" page-action="@ViewBag.PageAction"
         page-classes-enabled="true" page-class="btn" page-class-normal="btn-secondary"
         page-class-selected="btn-primary" class="btn-group text-center"></div>
</div>

Assignments/DealershipEFCore/DealershipEFCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="container-fluid">
        <h1 class="text-center">Hunter's Car Dealership Information</h1>
        <nav class="navbar navbar-light bg-light">
            <a asp-controller="AllVehicles" asp-action="List" asp-route-page="1">
                <input type="button" class="btn btn-outline-primary" value="All Vehicles In Dealership" />
            </a>

            <a asp-controller="SoldVehicles" asp-action="List" asp-route-page="1">
                <input type="button" class="btn btn-outline-primary" value="Vehicles Sold" />
            </a>

            <a asp-controller="Employees" asp-action="Index">
                <input type="button" class="btn btn-outline-primary" value="Employees" />
            </a>

            <a asp-controller="Customers" asp-action="List" asp-route-page="1">
                <input type="button" class="btn btn-outline-primary" value="Customer List" />
            </a>

            <a asp-controller="Invoices" asp-action="List" asp-route-page="1">
                <input type="button" class="btn btn-outline-primary" value="Invoices" />
            </a>

        </nav>
        <div class="container-fluid mt-4">
            @RenderBody()
        </div>
    </div>
</body>
</html>